# Generated by Django 4.2.13 on 2024-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('rating', models.FloatField()),
                ('url', models.URLField()),
                ('cuisine', models.CharField(max_length=100)),
                ('nutrition', models.JSONField()),
                ('timing', models.JSONField()),
            ],
        ),
    ]
