# Generated by Django 4.2.13 on 2024-07-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_favoriterecipe_alter_recipe_rating_alter_recipe_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='timing',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
